create extension if not exists pgcrypto;
-- pgvector is used for future RAG/embeddings
create extension if not exists vector;

create table if not exists market_snapshots(
  id bigint generated by default as identity primary key,
  symbol text not null,
  price numeric,
  change_24h numeric,
  volume_24h numeric,
  captured_at timestamptz not null,
  source text not null
);
create index if not exists market_snapshots_symbol_time on market_snapshots(symbol,captured_at desc);

create table if not exists derivative_snapshots(
  id bigint generated by default as identity primary key,
  symbol text not null,
  funding_rate numeric,
  open_interest numeric,
  captured_at timestamptz not null,
  source text not null
);
create index if not exists derivative_snapshots_symbol_time on derivative_snapshots(symbol,captured_at desc);

create table if not exists onchain_snapshots(
  id bigint generated by default as identity primary key,
  symbol text not null,
  holders bigint,
  transfers_24h bigint,
  captured_at timestamptz not null,
  source text not null
);
create index if not exists onchain_snapshots_symbol_time on onchain_snapshots(symbol,captured_at desc);

create table if not exists social_snapshots(
  id bigint generated by default as identity primary key,
  symbol text not null,
  mentions_24h bigint,
  sentiment numeric,
  captured_at timestamptz not null,
  source text not null
);
create index if not exists social_snapshots_symbol_time on social_snapshots(symbol,captured_at desc);

create table if not exists news_items(
  id bigint generated by default as identity primary key,
  symbol text not null,
  title text not null,
  url text not null unique,
  source text,
  description text,
  published_at timestamptz
);
create index if not exists news_items_symbol_time on news_items(symbol,published_at desc);

create table if not exists umbra_scores(
  id bigint generated by default as identity primary key,
  symbol text not null,
  total_score numeric not null,
  confidence numeric not null,
  inputs jsonb not null,
  calculated_at timestamptz not null
);
create index if not exists umbra_scores_symbol_time on umbra_scores(symbol,calculated_at desc);

create table if not exists radar_events(
  id bigint generated by default as identity primary key,
  symbol text not null,
  event text not null,
  severity text not null,
  confidence numeric not null,
  detail text not null,
  created_at timestamptz not null
);
create index if not exists radar_events_time on radar_events(created_at desc);

create table if not exists ai_reports(
  id bigint generated by default as identity primary key,
  symbol text,
  question text not null,
  answer text not null,
  data_context jsonb,
  created_at timestamptz not null default now()
);

alter table market_snapshots enable row level security;
alter table derivative_snapshots enable row level security;
alter table onchain_snapshots enable row level security;
alter table social_snapshots enable row level security;
alter table news_items enable row level security;
alter table umbra_scores enable row level security;
alter table radar_events enable row level security;
alter table ai_reports enable row level security;

create policy "public read market snapshots" on market_snapshots for select using (true);
create policy "public read derivative snapshots" on derivative_snapshots for select using (true);
create policy "public read onchain snapshots" on onchain_snapshots for select using (true);
create policy "public read social snapshots" on social_snapshots for select using (true);
create policy "public read news" on news_items for select using (true);
create policy "public read scores" on umbra_scores for select using (true);
create policy "public read radar" on radar_events for select using (true);
